# Generated by Django 3.1.4 on 2021-01-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0003_auto_20201224_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='checked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymeals.recipe'),
        ),
    ]
