# Generated by Django 3.1.4 on 2021-01-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0004_auto_20210111_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylistingredient',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
