# Generated by Django 3.1.4 on 2021-01-26 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0006_auto_20210123_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_recipe_ingredients', to='mymeals.recipe'),
        ),
    ]
