# Generated by Django 3.1.4 on 2021-01-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0009_recipe_category_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
