# Generated by Django 3.1.4 on 2021-01-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0010_remove_recipe_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='category_link',
            new_name='category',
        ),
    ]
