# Generated by Django 3.1.4 on 2021-01-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0011_auto_20210129_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
