# Generated by Django 3.1.4 on 2021-02-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0012_delete_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylistingredient',
            name='checked',
        ),
    ]
