# Generated by Django 3.1.4 on 2021-02-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0013_remove_mylistingredient_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='checked',
        ),
        migrations.AddField(
            model_name='mylistingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mymeals.recipe'),
        ),
    ]
