# Generated by Django 3.1.4 on 2021-02-02 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0014_auto_20210201_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='recipe_ingredients',
        ),
    ]
