# Generated by Django 3.1.4 on 2021-02-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0015_remove_grocerylist_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_instructions', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_instructions',
        ),
    ]
