# Generated by Django 3.1.4 on 2021-02-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0016_auto_20210205_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeinstruction',
            old_name='recipe_instructions',
            new_name='recipe_instruction',
        ),
        migrations.AddField(
            model_name='recipeinstruction',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymeals.recipe'),
        ),
    ]
