# Generated by Django 3.1.4 on 2021-02-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0019_auto_20210215_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(to='mymeals.Recipe'),
        ),
    ]
