# Generated by Django 3.1.4 on 2021-02-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymeals', '0020_user_favorite_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
